version: '3.8' # Versión del formato del archivo Compose
services: # Definimos los servicios que componen nuestra aplicación. En este caso, solo tenemos un servicio para MySQL.
  apirest-mysql-docker: # Definimos el servicio para MySQL, que se llamará "apirest-mysql-docker".
    image: mysql # Utilizamos la imagen oficial de MySQL. https://hub.docker.com/_/mysql/tags
    ports: # Defino el mapeo de puertos para acceder a MySQL desde la maquina alfitrion (host).
      - "3307:3306" # El primer puerto (3307) es el puerto del host, y el segundo puerto (3306) es el puerto del contenedor donde MySQL escucha por defecto.
    environment: # Definimos las variables de entorno para configurar el usuario administrador de MySQL.
      MYSQL_ROOT_PASSWORD: 123456
    volumes: # Definimos los volúmenes para persistir los datos de MySQL y montar el script de inicialización.
      - datos_mysql:/var/lib/mysql # Montamos un volumen llamado 'datos_mysql' para almacenar los datos de MySQL en el host, lo que permite que los datos persistan incluso si el contenedor se detiene o se elimina.
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql" # Montamos el script de inicialización para crear la base de datos y la colección al iniciar el contenedor.
    healthcheck: # Definimos una verificación de salud para el servicio de MySQL, lo que permite que otros servicios dependientes esperen a que MySQL esté listo antes de intentar conectarse.
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456" ]
      interval: 5s
      timeout: 5s
      retries: 10

  apirest-basica-mysql2: # Definimos el servicio para la aplicación de SpringBoot.
    build: . # Construimos la imagen de Docker para la aplicación de SpringBoot utilizando el Dockerfile ubicado en el directorio actual.
    ports: # Definimos el mapeo de puertos para acceder a la aplicación de SpringBoot desde la máquina anfitriona (host).
      - "8082:8082" # El primer puerto (8082) es el puerto del host, y el segundo puerto (8082) es el puerto del contenedor donde la aplicación de SpringBoot escucha por defecto.
    links: # Establecemos un enlace entre el servicio de la aplicación de SpringBoot y el servicio de MySQL, lo que permite que la aplicación de SpringBoot se comunique con MySQL utilizando el nombre del servicio como hostname.
      - apirest-mysql-docker
    depends_on: # Especificamos que este servicio depende del servicio de MySQL, lo que garantiza que MySQL se inicie antes que la aplicación de SpringBoot.
      apirest-mysql-docker:
        condition: service_healthy # Esto asegura que la aplicación de SpringBoot solo se inicie después de que MySQL esté listo y saludable, evitando problemas de conexión.

volumes: # Definimos los volúmenes que vamos a utilizar para persistir los datos de MySQL.
  datos_mysql: # Este volumen se utiliza para almacenar los datos de MySQL en el host, lo que permite que los datos persistan incluso si el contenedor se detiene o se elimina.